/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import type { Provider, TransactionRequest } from "@ethersproject/providers";
import type { Asm, AsmInterface } from "../Asm";

const _abi = [
  {
    inputs: [],
    name: "asmLoops",
    outputs: [
      {
        internalType: "uint256",
        name: "_r",
        type: "uint256",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256[]",
        name: "arr",
        type: "uint256[]",
      },
    ],
    name: "asmSumOfArray",
    outputs: [
      {
        internalType: "uint256",
        name: "sum",
        type: "uint256",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
];

const _bytecode =
  "0x608060405234801561001057600080fd5b506101bf806100206000396000f3fe608060405234801561001057600080fd5b50600436106100365760003560e01c80639c81ccc61461003b578063ebd22d9714610055575b600080fd5b610043610068565b60405190815260200160405180910390f35b6100436100633660046100cb565b61008b565b6000805b600a811015610081576001918201910161006c565b8160005260206000f35b600081516020830160005b828110156100ad5781519390930192600101610096565b505050919050565b634e487b7160e01b600052604160045260246000fd5b600060208083850312156100de57600080fd5b823567ffffffffffffffff808211156100f657600080fd5b818501915085601f83011261010a57600080fd5b81358181111561011c5761011c6100b5565b8060051b604051601f19603f83011681018181108582111715610141576101416100b5565b60405291825284820192508381018501918883111561015f57600080fd5b938501935b8285101561017d57843584529385019392850192610164565b9897505050505050505056fea264697066735822122085c300cd6c988b2bf3fd132d139c50dc18e0c6ea8ec69b6edc1a8ab65e4bee5b64736f6c634300080d0033";

type AsmConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: AsmConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class Asm__factory extends ContractFactory {
  constructor(...args: AsmConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override deploy(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<Asm> {
    return super.deploy(overrides || {}) as Promise<Asm>;
  }
  override getDeployTransaction(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  override attach(address: string): Asm {
    return super.attach(address) as Asm;
  }
  override connect(signer: Signer): Asm__factory {
    return super.connect(signer) as Asm__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): AsmInterface {
    return new utils.Interface(_abi) as AsmInterface;
  }
  static connect(address: string, signerOrProvider: Signer | Provider): Asm {
    return new Contract(address, _abi, signerOrProvider) as Asm;
  }
}
