/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "./common";

export interface AsmInterface extends utils.Interface {
  functions: {
    "asmLoops()": FunctionFragment;
    "asmSumOfArray(uint256[])": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic: "asmLoops" | "asmSumOfArray"
  ): FunctionFragment;

  encodeFunctionData(functionFragment: "asmLoops", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "asmSumOfArray",
    values: [BigNumberish[]]
  ): string;

  decodeFunctionResult(functionFragment: "asmLoops", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "asmSumOfArray",
    data: BytesLike
  ): Result;

  events: {};
}

export interface Asm extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: AsmInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    asmLoops(
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { _r: BigNumber }>;

    asmSumOfArray(
      arr: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { sum: BigNumber }>;
  };

  asmLoops(overrides?: CallOverrides): Promise<BigNumber>;

  asmSumOfArray(
    arr: BigNumberish[],
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  callStatic: {
    asmLoops(overrides?: CallOverrides): Promise<BigNumber>;

    asmSumOfArray(
      arr: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  filters: {};

  estimateGas: {
    asmLoops(overrides?: CallOverrides): Promise<BigNumber>;

    asmSumOfArray(
      arr: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    asmLoops(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    asmSumOfArray(
      arr: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
